src/com/poker_project/model/Jogador.java
package com.poker_project.model;

import java.io.Serializable;

//import javax.persistence.Entity;
//import javax.persistence.Id;

//@Entity
public class Jogador implements Serializable {
	
//	@Id
	
private static final long serialVersionUID = -309513637403441918L;
	
	private long id;
	private long id_torneio;
	private String nomeJogador;
	private String cpf;
	private String nomeFantasiaJogador;
	private String telefone;
	private String email;
	
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	
	public long getId_torneio() {
		return id_torneio;
	}
	public void setId_torneio(long id_torneio) {
		this.id_torneio = id_torneio;
	}
	public String getNomeJogador() {
		return nomeJogador;
	}
	public void setNomeJogador(String nomeJogador) {
		this.nomeJogador = nomeJogador;
	}
	public String getCpf() {
		return cpf;
	}
	public void setCpf(String cpf) {
		this.cpf = cpf;
	}
	public String getNomeFantasiaJogador() {
		return nomeFantasiaJogador;
	}
	public void setNomeFantasiaJogador(String nomeFantasiaJogador) {
		this.nomeFantasiaJogador = nomeFantasiaJogador;
	}
	public String getTelefone() {
		return telefone;
	}
	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	

}

src/com/poker_project/model/Torneio.java
package com.poker_project.model;

import java.io.Serializable;

public class Torneio implements Serializable  {
	
	private static final long serialVersionUID = -309513637403441918L;
	
	private long id;
	private String nomeTorneio;
	private String descricaoTorneio;
	private String premioTorneio;
	private String localTorneio;
	
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getNomeTorneio() {
		return nomeTorneio;
	}
	public void setNomeTorneio(String nomeTorneio) {
		this.nomeTorneio = nomeTorneio;
	}
	public String getDescricaoTorneio() {
		return descricaoTorneio;
	}
	public void setDescricaoTorneio(String descricaoTorneio) {
		this.descricaoTorneio = descricaoTorneio;
	}
	public String getPremioTorneio() {
		return premioTorneio;
	}
	public void setPremioTorneio(String premioTorneio) {
		this.premioTorneio = premioTorneio;
	}
	public String getLocalTorneio() {
		return localTorneio;
	}
	public void setLocalTorneio(String localTorneio) {
		this.localTorneio = localTorneio;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	
	

}

src/com/poker_project/manegedbeans/JogadorManagedBean.java
package com.poker_project.manegedbeans;

import java.sql.SQLException;
import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

//import com.poker_project.dao.DAO;
import com.poker_project.dao.JogadorDAO;
import com.poker_project.model.Jogador;
import com.poker_project.model.Torneio;
 

@ManagedBean(name="JogadorMB")
public class JogadorManagedBean {
     
     private Jogador jogador = new Jogador();
     private Torneio torneio = new Torneio();
     private int id_torneio;
     
     public void init() {
    	 FacesContext fc = FacesContext.getCurrentInstance();
    	 ExternalContext ec = fc.getExternalContext();
    	 Map<String,String> params = ec.getRequestParameterMap();
    	 String id = params.get("id");
    	 id_torneio = Integer.parseInt(id);
     }
     
     public String cadastraJogador() throws SQLException {
          
   		System.out.println("Teste aqui!!!");
	    JogadorDAO conexao = new JogadorDAO();         
	    
	    torneio.setId(id_torneio);
	    
	    if (conexao.inserirjogador(jogador, torneio)) {
	         FacesContext.getCurrentInstance().addMessage(
	          null, new FacesMessage(FacesMessage.SEVERITY_INFO,
	          "Sucesso!", "Jogador cadastrado com sucesso!"));
	    } else {
	         FacesContext.getCurrentInstance().addMessage(
	            null, new FacesMessage(FacesMessage.SEVERITY_ERROR,"Erro!", 
	            "Erro no cadastro do jogador!"));
	 
	                }
            //    conexao.closeConexao();
                
                
                
          return "";
     }

	public Jogador getJogador() {
		return jogador;
	}

	public void setJogador(Jogador jogador) {
		this.jogador = jogador;
	}

	public int getId_torneio() {
		return id_torneio;
	}

	public void setId_torneio(int id_torneio) {
		this.id_torneio = id_torneio;
	}
     
//     public List<Cadastro> getCadastros() throws SQLException {
// 
//          Conexao con = new Conexao();
//          List<Cadastro> listaCadastros = con.listaCadastros();
//     
//          return listaCadastros;
//     }
//     
//     public Cadastro getCadastro() {
//          return cadastro;
//     }
//     
//     public void setCadastro(Cadastro cadastro) {
//          this.cadastro = cadastro;
//     }
     
     
     
     
}
	
	
	
//}

src/com/poker_project/manegedbeans/TorneioManagedBean.java
package com.poker_project.manegedbeans;

import javax.faces.bean.ManagedBean;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import com.poker_project.model.Torneio;
import com.poker_project.dao.TorneioDAO;
import java.sql.SQLException;
import java.util.List;

@ManagedBean(name="TorneioMB")
public class TorneioManagedBean {
	
	     private Torneio torneio = new Torneio();
	     
	     public String cadastraTorneio() throws SQLException {
	          
	  	   		System.out.println("Teste aqui!!!");
	                TorneioDAO conexao = new TorneioDAO();         
	                
	                
	                if (conexao.inserirtorneio(torneio)) {
	                     FacesContext.getCurrentInstance().addMessage(
	                      null, new FacesMessage(FacesMessage.SEVERITY_INFO,
	                      "Sucesso!", "torneio cadastrado com sucesso!"));
	                } else {
	                     FacesContext.getCurrentInstance().addMessage(
	                        null, new FacesMessage(FacesMessage.SEVERITY_ERROR,"Erro!", 
	                        "Erro no cadastro do torneio!"));
	 
	                }      
	                
	                
	          return "";
	     }
	
	     
     public List<Torneio> getTorneios() throws SQLException {
	
          TorneioDAO conexao = new TorneioDAO();
	          List<Torneio> listaTorneios = conexao.listartorneio();
	     
          return listaTorneios;
	     }
	      
	     
     public Torneio gettorneio() {
			return torneio;
		}

		public void settorneio(Torneio torneio) {
			this.torneio = torneio;
		}
     
	}
		
		
		

	
	

WebContent/CadastroJogador.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"></meta>
	<title>Cadastro</title>
</h:head>
<h:body>
	<h:form id="mainForm">
		<p:messages id="messages" />

		<f:metadata>
			<f:viewParam name="id" value="#{JogadorMB.id_torneio}" />
			<f:viewAction action="#{JogadorMB.init}" />
		</f:metadata>

		<p:panel header="Cadastro de Jogador">
			<h:panelGrid columns="2" cellpadding="5">

				<p:outputLabel for="id" value="ID:" />
				<p:spinner readonly="true" id="id" value="#{JogadorMB.jogador.id}" />

				<p:outputLabel for="nomeJogador" value="Nome:" />
				<p:spinner id="nomeJogador" value="#{JogadorMB.jogador.nomeJogador}" />

				<p:outputLabel for="nomeFantasia" value="Nome Fantasia:" />
				<p:spinner id="nomeFantasia"
					value="#{JogadorMB.jogador.nomeFantasiaJogador}" />

				<p:outputLabel for="cpf" value="CPF:" />
				<p:spinner id="cpf" value="#{JogadorMB.jogador.cpf}" />

				<p:outputLabel for="telefone" value="Telefone:" />
				<p:spinner id="telefone" value="#{JogadorMB.jogador.telefone}" />

				<p:outputLabel for="email" value="Email:" />
				<p:spinner id="email" value="#{JogadorMB.jogador.email}" />

				<p:commandButton value="Cadastrar" icon="ui-icon-star"
					action="#{JogadorMB.cadastraJogador}" update="messages">
				</p:commandButton>


			</h:panelGrid>
		</p:panel>
	</h:form>
</h:body>
</html>

WebContent/CadastroTorneio.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">
<h:head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"></meta>
    <title>Cadastro Torneio</title>
</h:head>
<h:body>
    <h:form id="mainForm">
    	<p:messages id="messages" />
    	<p:panel header= "Cadastro de Torneio">
        <h:panelGrid columns="2" cellpadding="5">
       
        	<p:outputLabel for="id" value="ID:" />
                <p:spinner readonly="true" id="id" value="#{TorneioMB.torneio.id}" />
                
             <p:outputLabel for="nomeTorneio" value="Nome:" />
                <p:spinner id="nomeTorneio" value="#{TorneioMB.torneio.nomeTorneio}" /> 
                
             <p:outputLabel for="descricaoTorneio" value="Descricao:" />
                <p:spinner id="descricaoTorneio" value="#{TorneioMB.torneio.descricaoTorneio}" />   
             
              <p:outputLabel for="premioTorneio" value="Premiacao:" />
                <p:spinner id="premioTorneio" value="#{TorneioMB.torneio.premioTorneio}" />
                
              <p:outputLabel for="localTorneio" value="Local:" />
                <p:spinner id="localTorneio" value="#{TorneioMB.torneio.localTorneio}" />  
        	
           <p:commandButton  value="Cadastrar" icon="ui-icon-star" 
                 action="#{TorneioMB.cadastraTorneio}" update="messages">
                </p:commandButton>
  
  
        </h:panelGrid>
        </p:panel> 
    </h:form>
</h:body>
</html>

WebContent/ListagemTorneio.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
     xmlns:f="http://java.sun.com/jsf/core"
     xmlns:p="http://primefaces.org/ui">
  
<h:head>
  
</h:head>
  
<h:body>
     <h:form>
          <p:dataTable var="torneio" value="#{TorneioMB.torneios}">
                <p:column headerText="Id">
                     <h:outputText value="#{torneio.id}" />
                </p:column>
  
                <p:column headerText="Nome">
                     <h:outputText value="#{torneio.nomeTorneio}" />
                </p:column>
  
                <p:column headerText="Descricao">
                     <h:outputText value="#{torneio.descricaoTorneio}" />
                </p:column>
  
                <p:column headerText="Premiacao">
                     <h:outputText value="#{torneio.premioTorneio}" />
                </p:column>
                 
                <p:column headerText="Local">
                     <h:outputText value="#{torneio.localTorneio}" />
                </p:column>  
                
                <p:column headerText="Opcao">
                     <p:link outcome="index" value="Cadastrar Jogador">
    					<f:param name="id" value="#{torneio.id}" /> />
					 </p:link>
                </p:column>  
                             
          </p:dataTable>
  
  
     </h:form>
</h:body>
</html>